spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.mvc.routes[0].id=ms-usuario
spring.cloud.gateway.mvc.routes[0].uri=lb://ms-usuario
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/usuarios/**

spring.cloud.gateway.mvc.routes[1].id=mascota
spring.cloud.gateway.mvc.routes[1].uri=lb://mascota
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/mascotas/**

spring.cloud.gateway.mvc.routes[2].id=veterinario
spring.cloud.gateway.mvc.routes[2].uri=lb://veterinario
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/veterinarios/**

spring.cloud.gateway.mvc.routes[3].id=appointment-service
spring.cloud.gateway.mvc.routes[3].uri=lb://appointment-service
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/citas/**

spring.cloud.gateway.mvc.routes[4].id=diagnosis-service
spring.cloud.gateway.mvc.routes[4].uri=lb://diagnosis-service
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/diagnosticos/**

spring.cloud.gateway.mvc.routes[5].id=Inventario
spring.cloud.gateway.mvc.routes[5].uri=lb://inventario
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/productos/**

spring.cloud.gateway.mvc.routes[6].id=Proveedor
spring.cloud.gateway.mvc.routes[6].uri=lb://proveedor
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/proveedores/**

spring.cloud.gateway.mvc.routes[7].id=Movimientos
spring.cloud.gateway.mvc.routes[7].uri=lb://movimientos
spring.cloud.gateway.mvc.routes[7].predicates[0]=Path=/movimientos/**
